package DoctorOne.DoctorOne;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.Timer;

import net.dv8tion.jda.core.JDA;
import net.dv8tion.jda.core.entities.PrivateChannel;
import net.dv8tion.jda.core.entities.TextChannel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DoctorOne
 */
public class BotUI extends javax.swing.JPanel implements ActionListener{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form BotUI
     */
	private JDA bot;
    public BotUI(JDA bot) {
    	initComponents();
    	JFrame frame = new JFrame("Bot UI");
    	frame.add(this);
    	frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    	frame.pack();
    	frame.setVisible(true);
    	
    	this.bot = bot;
        Timer t = new Timer(10000,this);
        t.start();
    }

    private void go() {
    	//Get Lists
    	List<TextChannel> CList = bot.getTextChannels();
    	List<PrivateChannel> PList = bot.getPrivateChannels();
    	int i=0;
    	//Put Lists to Areas
    	PCList.setText("");
    	chanList.setText("");
    	for(PrivateChannel chan : PList) {
    		String current = chanList.getText();
    		chanList.setText(current + "\n" + i + ". " + chan.getName());
    		current = chanList.getText();
    		i++;
    	}
    	i=0;
    	for(TextChannel chan : CList) {
    		String current = PCList.getText();
    		PCList.setText(current + i + ". " + chan.getName() + ":\t" + chan.getGuild().getName() + "\n");
    		i++;
    	}
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
       // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sendArea = new javax.swing.JTextArea();
        sendKanal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PCList = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        chanList = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        chanNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sendPC = new javax.swing.JButton();
        PCNo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        Logger = new javax.swing.JTextArea();

        sendArea.setColumns(20);
        sendArea.setRows(5);
        jScrollPane1.setViewportView(sendArea);

        sendKanal.setText("Send Kanal");
        sendKanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendKanalActionPerformed(evt);
            }
        });

        PCList.setColumns(20);
        PCList.setRows(5);
        jScrollPane2.setViewportView(PCList);

        chanList.setColumns(20);
        chanList.setRows(5);
        jScrollPane3.setViewportView(chanList);

        jLabel1.setText("Kanal Listesi");

        jLabel2.setText("Kanal No");

        sendPC.setText("Send PC");
        sendPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendPCActionPerformed(evt);
            }
        });

        Logger.setColumns(20);
        Logger.setRows(5);
        jScrollPane4.setViewportView(Logger);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chanNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendKanal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PCNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sendPC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(sendKanal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sendPC, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(chanNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(14, 14, 14))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(PCNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
    }// </editor-fold>                        

    private void sendKanalActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    	List<TextChannel> CList = bot.getTextChannels();
    	TextChannel chan = CList.get(Integer.parseInt(chanNo.getText()));
    	chan.sendMessage(sendArea.getText()).queue();
    	String s = BotUI.Logger.getText();
		BotUI.Logger.setText(s + "mesaj gönderildi " + chan + "\n");
    }                                         

    private void sendPCActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    	List<PrivateChannel> PList = bot.getPrivateChannels();
    	PrivateChannel chan = PList.get(Integer.parseInt(PCNo.getText()));
    	chan.sendMessage(sendArea.getText()).queue();
    	String s = BotUI.Logger.getText();
		BotUI.Logger.setText(s + "mesaj gönderildi " + chan + "\n");
    } 

    // Variables declaration - do not modify
    public static javax.swing.JTextArea Logger;
    private javax.swing.JTextArea PCList;
    private javax.swing.JTextField PCNo;
    private javax.swing.JTextArea chanList;
    private javax.swing.JTextField chanNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea sendArea;
    private javax.swing.JButton sendKanal;
    private javax.swing.JButton sendPC;
    // End of variables declaration                   
	public void actionPerformed(ActionEvent arg0) {
		go();
		
	}
}

